routes/web.php
<?php

use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\MitraController as AdminMitraController;
use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Admin\ReviewController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\MitraController;
use App\Http\Controllers\ProductController;
use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('index');
// });

Route::prefix('/')->group(function () {
    Route::resource('/', IndexController::class);
    Route::resource('blog', BlogController::class)->only('index', 'show');
    Route::get('users/{id}', [MitraController::class, 'show'])->name('mitra.show');
    Route::get('product-list', [ProductController::class, 'index'])->name('product-list');
});


Route::prefix('adm-mandip')->middleware('auth')->name('admin.')->group(function () {
    Route::resource('/', HomeController::class);
    Route::get('blog/list', [BlogController::class, 'indexAdmin'])->name('blog.list');
    Route::resource('blog', BlogController::class);
    Route::resource('product', AdminProductController::class);
    Route::resource('mitra', AdminMitraController::class);
    Route::resource('review', ReviewController::class);
});

Auth::routes();

// block register
Route::get('/register', function() {
    return redirect('/login');
});

Route::post('/register', function() {
    return redirect('/login');
});


// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Mitra.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Mitra extends Model
{
    use HasFactory;
    protected $table = 'mitras';
    protected $fillable = [
        'name', 'image', 'content'
    ];
}

app/Http/Controllers/Admin/MitraController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Mitra;
use Illuminate\Http\Request;
use Validator;
use File;

class MitraController extends Controller
{
    public function index()
    {
        $data['data'] = Mitra::all();
        return view('admin.mitra.index', $data);
    }

    public function create()
    {
        return view('admin.mitra.create');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => ['required'],
            'image' => ['required|mimes:jpg, jpeg, png'],
        ]);

        if($request->hasFile('image')){
            $file = $request->file('image');
            $name = $request->name . '_' . time() . '.' . $file->getClientOriginalExtension();
            $file->move(public_path('images/available'), $name);
        };

        $data = Mitra::create([
            'name' => $request->name,
            'image' => $name,
            'content' => $request->content
        ]);

        Mitra::findOrFail($data->id);

        if ($data) {
            return redirect()->route('admin.mitra.index')->with('message', 'Berhasil menambahkan partner/mitra');
        } else {
            return back()->with('message', 'Gagal menambahkan partner/mitra');
        }
    }

    public function show(Mitra $mitra)
    {
        //
    }

    public function edit($id)
    {
        $data['data'] = Mitra::findOrFail($id);
        return view('admin.mitra.edit', $data);
    }

    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name' => ['required'],
            'image' => ['required|mimes:jpg, jpeg, png'],
        ]);

        $data = Mitra::findOrFail($id);

        if ($request->hasFile('image') == "") {
            $data->update([
                'name' => $request->name,
                'content' => $request->content
            ]);
            Mitra::findOrFail($data->id);
        } else {
            // hapus file lama
            $path = public_path("images/available/").$data->image;
            if (File::exists($path)) {
                unlink($path);
            }

            // tambah file baru
            $image = $request->file('image');
            $name = $request->name . '_' . time() . '.' . $image->getClientOriginalExtension();
            $image->move(public_path('images/available'), $name);

            $data->update([
                'name' => $request->name,
                'image' => $name,
                'content' => $request->content
            ]);
            Mitra::findOrFail($data->id);
        }

        if ($data) {
            return redirect()->route('admin.mitra.index')->with('message', 'Mitra berhasil diperbaharui');
        } else {
            return back()->with('message', 'Mitra gagal diperbaharui');
        }
    }

    public function destroy($id)
    {
        $data = Mitra::findOrFail($id);
        $path = public_path("images/available/").$data->image;
        if (File::exists($path)) {
            unlink($path);
        }
        $data->delete();
        return back()->with('message', 'Mitra telah dihapus');
    }
}

app/Http/Controllers/MitraController.php
<?php

namespace App\Http\Controllers;

use App\Models\Mitra;
use Illuminate\Http\Request;

class MitraController extends Controller
{
    public function show($id)
    {
        $data['mitra'] = Mitra::findOrFail($id);
        return view('mitra.show', $data);
    }
}

resources/views/admin/mitra/create.blade.php
@extends('admin.master')

@section('title')
    - Tambah Mitra
@endsection

@section('page-title')
    Tambah Mitra
@endsection

@section('breadcrumb')
    Tambah Mitra
@endsection

@section('js')
    <script src="https://cdn.tiny.cloud/1/fk6mrr5194u57okny3axnk6x9a0f6oxe74z9ufemtokfslbi/tinymce/5/tinymce.min.js"
        referrerpolicy="origin"></script>
    <script>
        tinymce.init({
            selector: 'textarea',
            plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table | align lineheight | numlist bullist indent outdent | emoticons charmap | removeformat',
        });
    </script>
    <script>
        document.querySelector('.custom-file-input').addEventListener('change', function(e) {
            var fileName = document.getElementById("customFile").files[0].name;
            var nextSibling = e.target.nextElementSibling
            nextSibling.innerText = fileName
        })
    </script>
@endsection

@section('content')
    <div class="card">
        <div class="card-body">
            <form action="{{ route('admin.mitra.store') }}" enctype="multipart/form-data" method="POST">
                @csrf
                @method('POST')
                <div class="form-group row">
                    <label for="name" class="col-sm-2 col-form-label">Nama Mitra</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="name" name="name" required placeholder="Nama Mitra">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="customFile" class="col-sm-2 col-form-label">Logo</label>
                    <div class="col-sm-10">
                        <div class="custom-file">
                            <input type="file" name="image" class="custom-file-input" required id="customFile">
                            <label class="custom-file-label" for="customFile">Choose file</label>
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="content" class="col-sm-2 col-form-label">Konten</label>
                    <div class="col-sm-10">
                        <textarea name="content" id="content" cols="30" rows="15"></textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-10">
                        <div class="col-sm-10">
                            <a class="btn btn-secondary btn-tone m-r-5" href="{{ url()->previous() }}">Kembali</a>
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/mitra/edit.blade.php
@extends('admin.master')

@section('title')
    - {{ $data->name }}
@endsection

@section('page-title')
    Ubah Mitra
@endsection

@section('breadcrumb')
    {{ $data->name }}
@endsection

@section('js')
    <script src="https://cdn.tiny.cloud/1/fk6mrr5194u57okny3axnk6x9a0f6oxe74z9ufemtokfslbi/tinymce/5/tinymce.min.js"
        referrerpolicy="origin"></script>
    <script>
        tinymce.init({
            selector: 'textarea',
            plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table | align lineheight | numlist bullist indent outdent | emoticons charmap | removeformat',
        });
    </script>
    <script>
        document.querySelector('.custom-file-input').addEventListener('change', function(e) {
            var fileName = document.getElementById("customFile").files[0].name;
            var nextSibling = e.target.nextElementSibling
            nextSibling.innerText = fileName
        })
    </script>
@endsection

@section('content')
    <div class="card">
        <div class="card-body">
            <form action="{{ route('admin.mitra.update', $data->id) }}" enctype="multipart/form-data" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group row">
                    <label for="name" class="col-sm-2 col-form-label">Nama Mitra</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="name" name="name" value="{{$data->name}}" required placeholder="Nama Mitra">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="customFile" class="col-sm-2 col-form-label">Gambar</label>
                    <div class="col-sm-10">
                        <div class="custom-file">
                            <input type="file" name="image" class="custom-file-input" id="customFile">
                            <label class="custom-file-label" for="customFile">{{$data->image}}</label>
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="content" class="col-sm-2 col-form-label">Konten</label>
                    <div class="col-sm-10">
                        <textarea name="content" id="content" cols="30" rows="15">{{ $data->content }}</textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-10">
                        <div class="col-sm-10">
                            <a class="btn btn-secondary btn-tone m-r-5" href="{{ url()->previous() }}">Kembali</a>
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/mitra/index.blade.php
@extends('admin.master')

@section('title')
    - Partner / Mitra
@endsection

@section('page-title')
    Partner / Mitra
@endsection

@section('breadcrumb')
    Partner / Mitra
@endsection

@section('css')
    <link href="{{ asset('admin/vendors/datatables/dataTables.bootstrap.min.css') }}" rel="stylesheet">

    <style>
        table img {
            width: 80px;
        }
    </style>
@endsection

@section('js')
    <script src="{{ asset('admin/vendors/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('admin/vendors/datatables/dataTables.bootstrap.min.js') }}"></script>

    <script>
        $('#data-table').DataTable();
    </script>
@endsection

@section('content')
    <div class="card">
        <div class="card-body">
            <div class="row justify-content-between mb-3">
                <div class="col-auto">
                    <h3>Daftar Mitra</h3>
                </div>
                <div class="col-auto">
                    <a href="{{ route('admin.mitra.create') }}" class="btn btn-primary">Tambah Mitra</a>
                </div>
            </div>
            <table id="data-table" class="table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Tanggal</th>
                        <th>Nama</th>
                        <th>Gambar</th>
                        <th>Ubah</th>
                        <th>Hapus</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($data as $value => $item)
                        <tr>
                            <td>{{ $value + 1 }}</td>
                            <td>{{ date('d-m-Y', strtotime($item->created_at)) }}</td>
                            <td>{{ $item->name }}</td>
                            <td>
                                <img src="{{ asset('images/available/'.$item->image) }}" alt="">
                            </td>
                            <td>
                                <a href="{{ route('admin.mitra.edit', $item->id) }}"
                                    class="btn btn-sm btn-primary btn-tone m-r-5">Ubah</a>
                            </td>
                            <td>
                                <form onsubmit="return confirm('Anda akan menghapus {{ $item->name }}?')"
                                    action="{{ route('admin.mitra.destroy', $item->id) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-sm btn-danger btn-tone m-r-5">Hapus</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <th>No</th>
                        <th>Tanggal</th>
                        <th>Nama</th>
                        <th>Gambar</th>
                        <th>Ubah</th>
                        <th>Hapus</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
@endsection