routes/web.php
<?php

use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\MitraController as AdminMitraController;
use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Admin\ReviewController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\MitraController;
use App\Http\Controllers\ProductController;
use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('index');
// });

Route::prefix('/')->group(function () {
    Route::resource('/', IndexController::class);
    Route::resource('blog', BlogController::class)->only('index', 'show');
    Route::get('users/{id}', [MitraController::class, 'show'])->name('mitra.show');
    Route::get('product-list', [ProductController::class, 'index'])->name('product-list');
});


Route::prefix('adm-mandip')->middleware('auth')->name('admin.')->group(function () {
    Route::resource('/', HomeController::class);
    Route::get('blog/list', [BlogController::class, 'indexAdmin'])->name('blog.list');
    Route::resource('blog', BlogController::class);
    Route::resource('product', AdminProductController::class);
    Route::resource('mitra', AdminMitraController::class);
    Route::resource('review', ReviewController::class);
});

Auth::routes();

// block register
Route::get('/register', function() {
    return redirect('/login');
});

Route::post('/register', function() {
    return redirect('/login');
});


// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/Admin/ReviewController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Review;
use Illuminate\Http\Request;

class ReviewController extends Controller
{
    public function index()
    {
        $data['data'] = Review::all();
        return view('admin.review.index', $data);
    }

    public function create()
    {
        return view('admin.review.create');
    }

    public function store(Request $request)
    {
        $data = Review::create([
            'name' => $request->name,
            'org' => $request->org,
            'position' => $request->position,
            'review' => $request->review,
        ]);

        Review::findOrFail($data->id);

        if ($data) {
            return redirect()->route('admin.review.index')->with('message', 'Berhasil menambahkan review');
        } else {
            return back()->with('message', 'Gagal menambahkan review');
        }
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $data['data'] = Review::findOrFail($id);
        return view('admin.review.edit', $data);
    }

    public function update(Request $request, $id)
    {
        $data = Review::findOrFail($id);

        $data->update([
            'name' => $request->name,
            'org' => $request->org,
            'position' => $request->position,
            'review' => $request->review,
        ]);
        Review::findOrFail($data->id);

        if ($data) {
            return redirect()->route('admin.review.index')->with('message', 'Review berhasil diperbaharui');
        } else {
            return back()->with('message', 'Review gagal diperbaharui');
        }
    }

    public function destroy($id)
    {
        $data = Review::findOrFail($id);
        $data->delete();
        return back()->with('message', 'Review telah dihapus');
    }
}

resources/views/admin/review/create.blade.php
@extends('admin.master')

@section('title')
    - Tambah Review
@endsection

@section('page-title')
    Tambah Review
@endsection

@section('breadcrumb')
    Review
@endsection

@section('content')
    <div class="card">
        <div class="card-body">
            <form action="{{ route('admin.review.store') }}" enctype="multipart/form-data" method="POST">
                @csrf
                @method('POST')
                <div class="form-group row">
                    <label for="name" class="col-sm-2 col-form-label">Nama</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="name" name="name" required placeholder="Nama">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="position" class="col-sm-2 col-form-label">Posisi</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="position" name="position" required placeholder="Posisi">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="org" class="col-sm-2 col-form-label">Perusahaan</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="org" name="org" placeholder="Perusahaan">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="review" class="col-sm-2 col-form-label">Review</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="review" name="review" required placeholder="Review">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-10">
                        <div class="col-sm-10">
                            <a class="btn btn-secondary btn-tone m-r-5" href="{{ url()->previous() }}">Kembali</a>
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/review/edit.blade.php
@extends('admin.master')

@section('title')
    - {{ $data->name }}
@endsection

@section('page-title')
    Ubah Review
@endsection

@section('breadcrumb')
    {{ $data->name }}
@endsection

@section('content')
    <div class="card">
        <div class="card-body">
            <form action="{{ route('admin.review.update', $data->id) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group row">
                    <label for="name" class="col-sm-2 col-form-label">Nama</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="name" name="name" value="{{$data->name}}" required placeholder="Nama">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="position" class="col-sm-2 col-form-label">Posisi</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="position" name="position" value="{{$data->position}}" required placeholder="Posisi">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="org" class="col-sm-2 col-form-label">Perusahaan</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="org" name="org" value="{{$data->org}}" placeholder="Perusahaan">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="review" class="col-sm-2 col-form-label">Review</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="review" name="review" value="{{$data->review}}" required placeholder="Review">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-10">
                        <div class="col-sm-10">
                            <a class="btn btn-secondary btn-tone m-r-5" href="{{ url()->previous() }}">Kembali</a>
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/review/index.blade.php
@extends('admin.master')

@section('title')
    - Review Para Pelanggan
@endsection

@section('page-title')
    Review Para Pelanggan
@endsection

@section('breadcrumb')
    Review
@endsection

@section('css')
    <link href="{{ asset('admin/vendors/datatables/dataTables.bootstrap.min.css') }}" rel="stylesheet">
@endsection

@section('js')
    <script src="{{ asset('admin/vendors/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('admin/vendors/datatables/dataTables.bootstrap.min.js') }}"></script>

    <script>
        $('#data-table').DataTable();
    </script>
@endsection

@section('content')
    <div class="card">
        <div class="card-body">
            <div class="row justify-content-between mb-3">
                <div class="col-auto">
                    <h3>Daftar Review</h3>
                </div>
                <div class="col-auto">
                    <a href="{{ route('admin.review.create') }}" class="btn btn-primary">Tambah Review</a>
                </div>
            </div>
            <table id="data-table" class="table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Tanggal</th>
                        <th>Nama</th>
                        <th>Jabatan</th>
                        <th>Organisasi</th>
                        <th>Ubah</th>
                        <th>Hapus</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($data as $value => $item)
                        <tr>
                            <td>{{ $value + 1 }}</td>
                            <td>{{ date('d-m-Y', strtotime($item->created_at)) }}</td>
                            <td>{{ $item->name }}</td>
                            <td>{{ $item->position }}</td>
                            <td>{{ $item->org }}</td>
                            <td>
                                <a href="{{ route('admin.review.edit', $item->id) }}"
                                    class="btn btn-sm btn-primary btn-tone m-r-5">Ubah</a>
                            </td>
                            <td>
                                <form onsubmit="return confirm('Anda akan menghapus {{ $item->name }}?')"
                                    action="{{ route('admin.review.destroy', $item->id) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-sm btn-danger btn-tone m-r-5">Hapus</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <th>No</th>
                        <th>Tanggal</th>
                        <th>Nama</th>
                        <th>Jabatan</th>
                        <th>Organisasi</th>
                        <th>Ubah</th>
                        <th>Hapus</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
@endsection