routes/web.php
<?php

use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\MitraController as AdminMitraController;
use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Admin\ReviewController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\MitraController;
use App\Http\Controllers\ProductController;
use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('index');
// });

Route::prefix('/')->group(function () {
    Route::resource('/', IndexController::class);
    Route::resource('blog', BlogController::class)->only('index', 'show');
    Route::get('users/{id}', [MitraController::class, 'show'])->name('mitra.show');
    Route::get('product-list', [ProductController::class, 'index'])->name('product-list');
});


Route::prefix('adm-mandip')->middleware('auth')->name('admin.')->group(function () {
    Route::resource('/', HomeController::class);
    Route::get('blog/list', [BlogController::class, 'indexAdmin'])->name('blog.list');
    Route::resource('blog', BlogController::class);
    Route::resource('product', AdminProductController::class);
    Route::resource('mitra', AdminMitraController::class);
    Route::resource('review', ReviewController::class);
});

Auth::routes();

// block register
Route::get('/register', function() {
    return redirect('/login');
});

Route::post('/register', function() {
    return redirect('/login');
});


// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $table = 'products';
    protected $fillable = [
        'name', 'price', 'image', 'status'
    ];
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Product;
use File;
use Illuminate\Http\Request;
use Validator;

class ProductController extends Controller
{
    public function index()
    {
        $send['data'] = Product::all();
        return view('admin.product.index', $send);
    }

    public function create()
    {
        return view('admin.product.create');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => ['required'],
            'image' => ['required|mimes:jpg, jpeg, png'],
        ]);

        if($request->hasFile('image')){
            $file = $request->file('image');
            $name = $request->name . '_' . time() . '.' . $file->getClientOriginalExtension();
            $file->move(public_path('images/products'), $name);
        };

        $data = Product::create([
            'name' => $request->name,
            'price' => $request->price,
            'image' => $name,
            'status' => $request->status,
            'slug' => strtolower(str_replace(' ', '-', $request->title))
        ]);

        Product::findOrFail($data->id);

        if ($data) {
            return redirect()->route('admin.product.index')->with('message', 'Berhasil menambahkan produk');
        } else {
            return back()->with('message', 'Gagal menambahkan produk');
        }
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $send['data'] = Product::findOrFail($id);
        return view('admin.product.edit', $send);
    }

    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'title' => ['required'],
            'desc' => ['required'],
            'image' => ['required|mimes:jpg, jpeg, png'],
        ]);

        $data = Product::findOrFail($id);

        if ($request->hasFile('image') == "") {
            $data->update([
                'name' => $request->name,
                'price' => $request->price,
                'status' => $request->status,
            ]);
            Product::findOrFail($data->id);
        } else {
            // hapus file lama
            $path = public_path("images/products/").$data->image;
            if (File::exists($path)) {
                unlink($path);
            }

            // tambah file baru
            $image = $request->file('image');
            $name = $request->name . '_' . time() . '.' . $image->getClientOriginalExtension();
            $image->move(public_path('images/products'), $name);

            $data->update([
                'name' => $request->name,
                'price' => $request->price,
                'status' => $request->status,
                'image' => $name,
            ]);
            Product::findOrFail($data->id);
        }

        if ($data) {
            return redirect()->route('admin.product.index')->with('message', 'Product berhasil diperbaharui');
        } else {
            return back()->with('message', 'Product gagal diperbaharui');
        }
    }

    public function destroy($id)
    {
        $data = Product::findOrFail($id);
        $path = public_path("images/products/").$data->image;
        if (File::exists($path)) {
            unlink($path);
        }
        $data->delete();
        return back()->with('message', 'Produk telah dihapus');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function index()
    {
        $data['product'] = Product::paginate(10);
        return view('product-list', $data);
    }
}

resources/views/admin/product/create.blade.php
@extends('admin.master')

@section('title')
    - Tambah Product
@endsection

@section('page-title')
    Tambah Product
@endsection

@section('breadcrumb')
    Tambah Product
@endsection

@section('js')
    <script>
        document.querySelector('.custom-file-input').addEventListener('change', function(e) {
            var fileName = document.getElementById("customFile").files[0].name;
            var nextSibling = e.target.nextElementSibling
            nextSibling.innerText = fileName
        })
    </script>
@endsection

@section('content')
    <div class="card">
        <div class="card-body">
            <form action="{{ route('admin.product.store') }}" enctype="multipart/form-data" method="POST">
                @csrf
                @method('POST')
                <div class="form-group row">
                    <label for="name" class="col-sm-2 col-form-label">Nama Produk</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="name" name="name" required placeholder="Nama Produk">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="price" class="col-sm-2 col-form-label">Harga (Opsional) </label>
                    <div class="col-sm-10">
                        <input type="number" class="form-control" id="price" name="price" placeholder="Harga">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="customFile" class="col-sm-2 col-form-label">Gambar</label>
                    <div class="col-sm-10">
                        <div class="custom-file">
                            <input type="file" name="image" class="custom-file-input" required id="customFile">
                            <label class="custom-file-label" for="customFile">Choose file</label>
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2">Status</div>
                    <div class="col-sm-10">
                        <div class="checkbox">
                            <input type="checkbox" name="status" checked id="gridCheck1">
                            <label for="gridCheck1">
                                Aktif
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-10">
                        <div class="col-sm-10">
                            <a class="btn btn-secondary btn-tone m-r-5" href="{{ url()->previous() }}">Kembali</a>
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/product/edit.blade.php
@extends('admin.master')

@section('title')
    - {{ $data->name }}
@endsection

@section('page-title')
    Ubah Product
@endsection

@section('breadcrumb')
    {{ $data->name }}
@endsection

@section('js')
    <script>
        document.querySelector('.custom-file-input').addEventListener('change', function(e) {
            var fileName = document.getElementById("customFile").files[0].name;
            var nextSibling = e.target.nextElementSibling
            nextSibling.innerText = fileName
        })
    </script>
@endsection

@section('content')
    <div class="card">
        <div class="card-body">
            <form action="{{ route('admin.product.update', $data->id) }}" enctype="multipart/form-data" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group row">
                    <label for="name" class="col-sm-2 col-form-label">Nama Produk</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="name" name="name" value="{{$data->name}}" required placeholder="Nama Produk">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="price" class="col-sm-2 col-form-label">Harga (Opsional) </label>
                    <div class="col-sm-10">
                        <input type="number" class="form-control" id="price" name="price" value="{{$data->price}}" placeholder="Harga">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="customFile" class="col-sm-2 col-form-label">Gambar</label>
                    <div class="col-sm-10">
                        <div class="custom-file">
                            <input type="file" name="image" class="custom-file-input" id="customFile">
                            <label class="custom-file-label" for="customFile">{{$data->image}}</label>
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2">Status</div>
                    <div class="col-sm-10">
                        <div class="checkbox">
                            <input type="checkbox" name="status"  {{ $data->status != null ? 'checked' : '' }} id="gridCheck1">
                            <label for="gridCheck1">
                                Aktif
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-10">
                        <div class="col-sm-10">
                            <a class="btn btn-secondary btn-tone m-r-5" href="{{ url()->previous() }}">Kembali</a>
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/product/index.blade.php
@extends('admin.master')

@section('title')
    - Produk
@endsection

@section('page-title')
    Produk
@endsection

@section('breadcrumb')
    Produk
@endsection

@section('css')
    <link href="{{ asset('admin/vendors/datatables/dataTables.bootstrap.min.css') }}" rel="stylesheet">

    <style>
        .td-title {
            width: 55vh;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
            color: #5A5A66;
        }

    </style>
@endsection

@section('js')
    <script src="{{ asset('admin/vendors/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('admin/vendors/datatables/dataTables.bootstrap.min.js') }}"></script>

    <script>
        $('#data-table').DataTable();
    </script>
@endsection

@section('content')
    <div class="card">
        <div class="card-body">
            <div class="row justify-content-between mb-3">
                <div class="col-auto">
                    <h3>Daftar Product</h3>
                </div>
                <div class="col-auto">
                    <a href="{{ route('admin.product.create') }}" class="btn btn-primary">Tambah Produk</a>
                </div>
            </div>
            <table id="data-table" class="table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Tanggal</th>
                        <th>Produk</th>
                        <th>Harga</th>
                        <th>Status</th>
                        <th>Ubah</th>
                        <th>Hapus</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($data as $value => $item)
                        <tr>
                            <td>{{ $value + 1 }}</td>
                            <td>{{ date('d-m-Y', strtotime($item->created_at)) }}</td>
                            <td>{{ $item->name }}</td>
                            <td>{{ $item->price != null ? $item->price : '0' }}</td>
                            <td>
                                @if ($item->status != null)
                                    <span class="badge badge-pill badge-info">Show</span>
                                @else
                                    <span class="badge badge-pill badge-warning">Hidden</span>
                                @endif
                            </td>
                            <td><a href="{{ route('admin.product.edit', $item->id) }}"
                                    class="btn btn-sm btn-primary btn-tone m-r-5">Ubah</a></td>
                            <td>
                                <form onsubmit="return confirm('Anda akan menghapus {{ $item->name }}?')"
                                    action="{{ route('admin.product.destroy', $item->id) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-sm btn-danger btn-tone m-r-5">Hapus</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <th>No</th>
                        <th>Tanggal</th>
                        <th>Produk</th>
                        <th>Harga</th>
                        <th>Status</th>
                        <th>Ubah</th>
                        <th>Hapus</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
@endsection