routes/web.php
<?php

use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\MitraController as AdminMitraController;
use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Admin\ReviewController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\MitraController;
use App\Http\Controllers\ProductController;
use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('index');
// });

Route::prefix('/')->group(function () {
    Route::resource('/', IndexController::class);
    Route::resource('blog', BlogController::class)->only('index', 'show');
    Route::get('users/{id}', [MitraController::class, 'show'])->name('mitra.show');
    Route::get('product-list', [ProductController::class, 'index'])->name('product-list');
});


Route::prefix('adm-mandip')->middleware('auth')->name('admin.')->group(function () {
    Route::resource('/', HomeController::class);
    Route::get('blog/list', [BlogController::class, 'indexAdmin'])->name('blog.list');
    Route::resource('blog', BlogController::class);
    Route::resource('product', AdminProductController::class);
    Route::resource('mitra', AdminMitraController::class);
    Route::resource('review', ReviewController::class);
});

Auth::routes();

// block register
Route::get('/register', function() {
    return redirect('/login');
});

Route::post('/register', function() {
    return redirect('/login');
});


// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;
    protected $table = 'blogs';
    protected $fillable = [
        'slug', 'title', 'desc', 'image', 'status'
    ];
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Blog;
use Validator;
use File;

class BlogController extends Controller
{
    public function index()
    {
        $data['blog'] = Blog::all();
        return view('blog.index', $data);
    }

    public function indexAdmin()
    {
        $send['data'] = Blog::all();
        return view('admin.blog.index', $send);
    }

    public function create()
    {
        return view('admin.blog.create');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title' => ['required'],
            'desc' => ['required'],
            'image' => ['required|mimes:jpg, jpeg, png'],
        ]);

        if($request->hasFile('image')){
            $file = $request->file('image');
            $name = 'blog_' . time() . '.' . $file->getClientOriginalExtension();
            $file->move(public_path('images/blog'), $name);
        };

        $data = Blog::create([
            'title' => $request->title,
            'desc' => $request->desc,
            'image' => $name,
            'status' => $request->status,
            'slug' => strtolower(str_replace(' ', '-', $request->title))
        ]);

        Blog::findOrFail($data->id)->update(['slug' => $data->slug.'-'.time()]);

        if ($data) {
            return redirect()->route('admin.blog.list')->with('message', 'Berhasil membuat blog');
        } else {
            return back()->with('message', 'Gagal membuat blog');
        }
    }

    public function show($slug)
    {
        $data['blog'] = Blog::where('slug', $slug)->first();
        return view('blog.show', $data);
    }

    public function edit($id)
    {
        $send['data'] = Blog::findOrFail($id);
        return view('admin.blog.edit', $send);
    }

    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'title' => ['required'],
            'desc' => ['required'],
            'image' => ['required|mimes:jpg, jpeg, png'],
        ]);

        $data = Blog::findOrFail($id);

        if ($request->hasFile('image') == "") {
            $data->update([
                'title' => $request->title,
                'desc' => $request->desc,
                'status' => $request->status,
                'slug' => strtolower(str_replace(' ', '-', $request->title))
            ]);
            Blog::findOrFail($data->id)->update(['slug' => $data->slug.'-'.$data->id]);
        } else {
            // hapus file lama
            $path = public_path("images/blog/").$data->image;
            if (File::exists($path)) {
                unlink($path);
            }

            // tambah file baru
            $image = $request->file('image');
            $name = 'blog_' . time() . '.' . $image->getClientOriginalExtension();
            $image->move(public_path('images/blog'), $name);

            $data->update([
                'title' => $request->title,
                'desc' => $request->desc,
                'status' => $request->status,
                'image' => $name,
                'slug' => strtolower(str_replace(' ', '-', $request->title))
            ]);
            Blog::findOrFail($data->id)->update(['slug' => $data->slug.'-'.time()]);
        }

        if ($data) {
            return redirect()->route('admin.blog.list')->with('message', 'Blog berhasil diperbaharui');
        } else {
            return back()->with('message', 'Blog gagal diperbaharui');
        }
    }

    public function destroy($id)
    {
        $data = Blog::findOrFail($id);
        $path = public_path("images/blog/").$data->image;
        if (File::exists($path)) {
            unlink($path);
        }
        $data->delete();
        return back()->with('message', 'Blog telah dihapus');
    }
}

resources/views/admin/blog/create.blade.php
@extends('admin.master')

@section('title')
    - Buat Blog
@endsection

@section('page-title')
    Buat Blog
@endsection

@section('breadcrumb')
    Buat Blog
@endsection

@section('css')
    <link href="{{ asset('admin/vendors/datatables/dataTables.bootstrap.min.css') }}" rel="stylesheet">
@endsection

@section('js')
    <script src="https://cdn.tiny.cloud/1/fk6mrr5194u57okny3axnk6x9a0f6oxe74z9ufemtokfslbi/tinymce/5/tinymce.min.js"
        referrerpolicy="origin"></script>

    <script>
        tinymce.init({
            selector: 'textarea',
            plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table | align lineheight | numlist bullist indent outdent | emoticons charmap | removeformat',
        });
    </script>

    <script>
        document.querySelector('.custom-file-input').addEventListener('change', function(e) {
            var fileName = document.getElementById("customFile").files[0].name;
            var nextSibling = e.target.nextElementSibling
            nextSibling.innerText = fileName
        })
    </script>
@endsection

@section('content')
    <div class="card">
        <div class="card-body">
            <form action="{{ route('admin.blog.store') }}" enctype="multipart/form-data" method="POST">
                @csrf
                @method('POST')
                <div class="form-group row">
                    <label for="title" class="col-sm-2 col-form-label">Judul</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="title" name="title" placeholder="Judul">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="desc" class="col-sm-2 col-form-label">Deskripsi</label>
                    <div class="col-sm-10">
                        <textarea name="desc" id="desc" cols="30" rows="15"></textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="customFile" class="col-sm-2 col-form-label">Gambar</label>
                    <div class="col-sm-10">
                        <div class="custom-file">
                            <input type="file" name="image" class="custom-file-input" id="customFile">
                            <label class="custom-file-label" for="customFile">Choose file</label>
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2">Status</div>
                    <div class="col-sm-10">
                        <div class="checkbox">
                            <input type="checkbox" name="status" checked id="gridCheck1">
                            <label for="gridCheck1">
                                Aktif
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-10">
                        <div class="col-sm-10">
                            <a class="btn btn-secondary btn-tone m-r-5" href="{{ url()->previous() }}">Kembali</a>
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/blog/edit.blade.php
@extends('admin.master')

@section('title')
    - {{ $data->title }}
@endsection

@section('page-title')
    Edit Blog
@endsection

@section('breadcrumb')
    edit blog : {{ $data->title }}
@endsection

@section('css')
    <link href="{{ asset('admin/vendors/datatables/dataTables.bootstrap.min.css') }}" rel="stylesheet">
@endsection

@section('js')
    <script src="https://cdn.tiny.cloud/1/fk6mrr5194u57okny3axnk6x9a0f6oxe74z9ufemtokfslbi/tinymce/5/tinymce.min.js"
        referrerpolicy="origin"></script>

    <script>
        tinymce.init({
            selector: 'textarea',
            plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table | align lineheight | numlist bullist indent outdent | emoticons charmap | removeformat',
        });
    </script>

    <script>
        document.querySelector('.custom-file-input').addEventListener('change', function(e) {
            var fileName = document.getElementById("customFile").files[0].name;
            var nextSibling = e.target.nextElementSibling
            nextSibling.innerText = fileName
        })
    </script>
@endsection

@section('content')
    <div class="card">
        <div class="card-body">
            <form action="{{ route('admin.blog.update', $data->id) }}" enctype="multipart/form-data" method="POST">
                @csrf
                @method('PUT')
                <div class="form-group row">
                    <label for="title" class="col-sm-2 col-form-label">Judul</label>
                    <div class="col-sm-10">
                        <input type="text" value="{{ $data->title }}" class="form-control" id="title" name="title"
                            placeholder="Judul">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="desc" class="col-sm-2 col-form-label">Deskripsi</label>
                    <div class="col-sm-10">
                        <textarea name="desc" id="desc" cols="30" rows="10">
                                        {{ $data->desc }}
                                    </textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="customFile" class="col-sm-2 col-form-label">Gambar</label>
                    <div class="col-sm-10">
                        <div class="custom-file">
                            <input type="file" name="image" class="custom-file-input" id="customFile">
                            <label class="custom-file-label" for="customFile">{{ $data->image }}</label>
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2">Status</div>
                    <div class="col-sm-10">
                        <div class="checkbox">
                            <input type="checkbox" name="status" {{ $data->status != null ? 'checked' : '' }}
                                id="gridCheck1">
                            <label for="gridCheck1">
                                Aktif
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-10">
                        <div class="col-sm-10">
                            <a class="btn btn-secondary btn-tone m-r-5" href="{{ url()->previous() }}">Kembali</a>
                            <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/blog/index.blade.php
@extends('admin.master')

@section('title')
    - Blog
@endsection

@section('page-title')
    Blog
@endsection

@section('breadcrumb')
    Blog
@endsection

@section('css')
    <link href="{{ asset('admin/vendors/datatables/dataTables.bootstrap.min.css') }}" rel="stylesheet">

    <style>
        .td-title {
            width: 55vh;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
            color: #5A5A66;
        }

    </style>
@endsection

@section('js')
    <script src="{{ asset('admin/vendors/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('admin/vendors/datatables/dataTables.bootstrap.min.js') }}"></script>

    <script>
        $('#data-table').DataTable();
    </script>
@endsection

@section('content')
    <div class="card">
        <div class="card-body">
            <div class="row justify-content-between mb-3">
                <div class="col-auto">
                    <h3>Daftar Blog</h3>
                </div>
                <div class="col-auto">
                    <a href="{{ route('admin.blog.create') }}" class="btn btn-primary">Buat baru</a>
                </div>
            </div>
            <table id="data-table" class="table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Tanggal</th>
                        <th>Judul</th>
                        <th>Status</th>
                        <th>Ubah</th>
                        <th>Hapus</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($data as $value => $item)
                        <tr>
                            <td>{{ $value + 1 }}</td>
                            <td>{{ date('d-m-Y', strtotime($item->created_at)); }}</td>
                            <td>
                                <a href="{{route('blog.show', $item->slug)}}" target="_blank" class="td-title">{{ $item->title }}</a>
                            </td>
                            <td>
                                @if ($item->status != null)
                                    <span class="badge badge-pill badge-info">Show</span>
                                @else
                                    <span class="badge badge-pill badge-warning">Hidden</span>
                                @endif
                            </td>
                            <td><a href="{{ route('admin.blog.edit', $item->id) }}"
                                    class="btn btn-sm btn-primary btn-tone m-r-5">Ubah</a></td>
                            <td>
                                <form onsubmit="return confirm('Anda akan menghapus {{ $item->title }}?')"
                                    action="{{ route('admin.blog.destroy', $item->id) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-sm btn-danger btn-tone m-r-5">Hapus</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <th>No</th>
                        <th>Tanggal</th>
                        <th>Judul</th>
                        <th>Status</th>
                        <th>Ubah</th>
                        <th>Hapus</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
@endsection